# Generated by Django 4.0.6 on 2022-08-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='password',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='photo',
        ),
    ]
