# Generated by Django 4.0.6 on 2022-08-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_remove_coach_password_remove_coach_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='dateBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
    ]
