# Generated by Django 2.2.12 on 2022-02-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Назва')),
                ('city', models.CharField(max_length=20, verbose_name='Місто')),
                ('adress', models.CharField(max_length=35, verbose_name='Вулиця')),
                ('is_active', models.BooleanField(default=True, verbose_name='Працює?')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.Coach')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школи',
            },
        ),
    ]
