# Generated by Django 2.2.12 on 2022-02-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220203_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Coach'),
        ),
    ]
