# Generated by Django 2.2.12 on 2022-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220205_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belt',
            options={'verbose_name': 'Пояс', 'verbose_name_plural': 'Пояси'},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='belt',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='belt',
        ),
        migrations.AlterField(
            model_name='belt',
            name='kyu',
            field=models.IntegerField(verbose_name='Кю'),
        ),
    ]
