# Generated by Django 2.2.12 on 2022-02-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Прізвище')),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='По батькові')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Пароль')),
                ('dateBirth', models.DateField(verbose_name='Дата народження')),
                ('telephone', models.IntegerField(verbose_name='Номер телефону')),
                ('telephone2', models.IntegerField(blank=True, null=True, verbose_name='Номер телефону 2')),
                ('belt', models.SmallIntegerField(choices=[(0, 'Білий пояс'), (10, '10 кю'), (9, '9 кю'), (8, '8 кю'), (7, '7 кю'), (6, '6 кю'), (5, '5 кю'), (4, '4 кю'), (3, '3 кю'), (2, '2 кю'), (1, '1 кю'), (11, '1 дан'), (12, '2 дан'), (13, '3 дан'), (14, '4 дан'), (15, '5 дан'), (16, '6 дан'), (17, '7 дан'), (18, '8 дан'), (19, '9 дан')], verbose_name='Рівень поясу')),
                ('information', models.TextField(verbose_name='Інформація про тренера')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Тренує?')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренери',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Імя')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15, verbose_name='День')),
                ('timeStart', models.TimeField(verbose_name='Час початку')),
                ('timeFinish', models.TimeField(verbose_name='Час завершення')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
            ],
            options={
                'verbose_name': 'Графік',
                'verbose_name_plural': 'Графіки',
            },
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Прізвище')),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='По батькові')),
                ('dateBirth', models.DateField(verbose_name='Дата народження')),
                ('telephone', models.IntegerField(verbose_name='Номер телефону')),
                ('belt', models.SmallIntegerField(choices=[(0, 'Білий пояс'), (10, '10 кю'), (9, '9 кю'), (8, '8 кю'), (7, '7 кю'), (6, '6 кю'), (5, '5 кю'), (4, '4 кю'), (3, '3 кю'), (2, '2 кю'), (1, '1 кю'), (11, '1 дан'), (12, '2 дан'), (13, '3 дан'), (14, '4 дан'), (15, '5 дан'), (16, '6 дан'), (17, '7 дан'), (18, '8 дан'), (19, '9 дан')], verbose_name='Рівень поясу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Тренується?')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Coach')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмени',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Назва')),
                ('city', models.CharField(max_length=20, verbose_name='Місто')),
                ('adress', models.CharField(max_length=35, verbose_name='Вулиця')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Coach')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школи',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
    ]
