# Generated by Django 2.2.12 on 2022-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220203_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='belt',
            field=models.SmallIntegerField(choices=[(0, 'Білий пояс'), (10, '10 кю'), (9, '9 кю'), (8, '8 кю'), (7, '7 кю'), (6, '6 кю'), (5, '5 кю'), (4, '4 кю'), (3, '3 кю'), (2, '2 кю'), (1, '1 кю'), (11, '1 дан'), (12, '2 дан'), (13, '3 дан'), (14, '4 дан'), (15, '5 дан'), (16, '6 дан'), (17, '7 дан'), (18, '8 дан'), (19, '9 дан')], default=0, null=True, verbose_name='Рівень поясу'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='belt',
            field=models.SmallIntegerField(choices=[(0, 'Білий пояс'), (10, '10 кю'), (9, '9 кю'), (8, '8 кю'), (7, '7 кю'), (6, '6 кю'), (5, '5 кю'), (4, '4 кю'), (3, '3 кю'), (2, '2 кю'), (1, '1 кю'), (11, '1 дан'), (12, '2 дан'), (13, '3 дан'), (14, '4 дан'), (15, '5 дан'), (16, '6 дан'), (17, '7 дан'), (18, '8 дан'), (19, '9 дан')], default=0, null=True, verbose_name='Рівень поясу'),
        ),
    ]
