# Generated by Django 2.2.12 on 2022-02-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_group_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Coach'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Coach'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Group'),
        ),
    ]
