# Generated by Django 2.2.12 on 2022-02-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_school_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, upload_to='coach/photo/%Y/', verbose_name='Фото'),
        ),
    ]
