# Generated by Django 2.2.12 on 2022-02-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220205_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='belts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Belt'),
        ),
        migrations.AddField(
            model_name='sportsman',
            name='belts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Belt'),
        ),
    ]
