# Generated by Django 2.2.12 on 2022-02-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15, verbose_name='День')),
                ('timeStart', models.TimeField(verbose_name='Час початку')),
                ('timeFinish', models.TimeField(verbose_name='Час завершення')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
            options={
                'verbose_name': 'Графік',
                'verbose_name_plural': 'Графіки',
            },
        ),
    ]
