# Generated by Django 2.2.12 on 2022-02-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='slug',
        ),
    ]
