# Generated by Django 2.2.12 on 2022-02-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20220208_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='days',
            field=models.CharField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, 'Пятниця'), (5, 'Субота'), (6, 'Неділя')], max_length=1),
        ),
    ]
