# Generated by Django 2.2.12 on 2022-02-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetable_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
