# Generated by Django 2.2.12 on 2022-02-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20220208_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='days',
            field=models.CharField(choices=[('Mon', 'Понеділок'), ('Tue', 'Вівторок'), ('Wed', 'Середа'), ('Thu', 'Четвер'), ('Fri', 'Пятниця'), ('Sat', 'Субота'), ('Sun', 'Неділя')], max_length=5),
        ),
    ]
