# Generated by Django 2.2.12 on 2022-02-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20220208_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='days',
            field=models.CharField(choices=[('Понеділок', 'Понеділок'), ('Вівторок', 'Вівторок'), ('Середа', 'Середа'), ('Четвер', 'Четвер'), ('Пятниця', 'Пятниця'), ('Субота', 'Субота'), ('Неділя', 'Неділя')], max_length=15),
        ),
    ]
