# Generated by Django 2.2.12 on 2022-02-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20220209_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='days',
        ),
        migrations.AddField(
            model_name='timetable',
            name='days',
            field=models.ManyToManyField(blank=True, to='timetable.TimetableDays'),
        ),
    ]
