# Generated by Django 4.0.6 on 2022-08-04 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Імя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.CreateModel(
            name='TimetableDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дні тиждня',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStart', models.TimeField(verbose_name='Час початку')),
                ('timeFinish', models.TimeField(verbose_name='Час завершення')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('days', models.ManyToManyField(blank=True, to='dodjo.timetabledays')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dodjo.group')),
            ],
            options={
                'verbose_name': 'Графік',
                'verbose_name_plural': 'Графіки',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Назва')),
                ('city', models.CharField(max_length=20, verbose_name='Місто')),
                ('adress', models.CharField(max_length=35, verbose_name='Вулиця')),
                ('is_active', models.BooleanField(default=True, verbose_name='Працює?')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школи',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dodjo.school'),
        ),
    ]
