# Generated by Django 4.0.6 on 2022-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodjo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='test',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тест'),
        ),
    ]
