# Generated by Django 4.0.6 on 2022-08-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodjo', '0002_timetable_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='test',
        ),
    ]
