# Generated by Django 4.0.6 on 2022-08-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodjo', '0004_group_costmoon_group_costtraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Назва'),
        ),
    ]
