# Generated by Django 2.2.12 on 2022-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назва')),
                ('kyu', models.IntegerField(verbose_name='Кю')),
                ('img', models.ImageField(blank=True, upload_to='belt/%Y/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пояс',
                'verbose_name_plural': 'Пояси',
            },
        ),
    ]
