# Generated by Django 2.2.12 on 2022-02-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belt',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
