# Generated by Django 2.2.12 on 2022-02-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_auto_20220208_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belt',
            name='kyu',
        ),
        migrations.AddField(
            model_name='belt',
            name='fullname',
            field=models.CharField(default='0', max_length=100, verbose_name='Повна назва'),
        ),
        migrations.AddField(
            model_name='belt',
            name='number',
            field=models.IntegerField(default='0', verbose_name='Цифра пояса'),
        ),
        migrations.AlterField(
            model_name='belt',
            name='img',
            field=models.ImageField(blank=True, upload_to='belt/%Y/', verbose_name='Картинка'),
        ),
    ]
