# Generated by Django 2.2.12 on 2022-02-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_auto_20220208_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belt',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Повна назва'),
        ),
        migrations.AlterField(
            model_name='belt',
            name='number',
            field=models.IntegerField(verbose_name='Цифра пояса'),
        ),
    ]
