# Generated by Django 2.2.12 on 2022-02-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
        ('group', '0001_initial'),
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Прізвище')),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='По батькові')),
                ('dateBirth', models.DateField(verbose_name='Дата народження')),
                ('telephone', models.IntegerField(verbose_name='Номер телефону')),
                ('is_active', models.BooleanField(default=True, verbose_name='Тренується?')),
                ('belts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='belt.Belt')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.Coach')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.Group')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмени',
            },
        ),
    ]
