# Generated by Django 4.0.6 on 2022-08-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='dateBirth',
            field=models.DateField(blank=True, verbose_name='Дата народження'),
        ),
    ]
