# Generated by Django 2.2.12 on 2022-02-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_auto_20220211_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
